### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 () cocoen.min.js

### ISSUE THREAD

**Issue by brendaboudaie** [koenoe/cocoen#51]
I installed cocoen with npm, included the stylesheet and the script in my index.html file, created the package.json, and it works fine when testing from my local computer.

When I push to my github (github pages), I get 'Failed to load resource: the server responded with a status of 404 ()' for both the cocoen.min.css and cocoen.min.js. I connected the package.json with the repo and tried to change the css and js paths but the files still can't be found.

Here's my repo: https://github.com/brendaboudaie/brendaboudaie.github.io/blob/master/index.html.

Appreciate any help!

**Comment by frankie-tech** [comment]
I see you got things working! It sounds like your problem is semi-solved.

As for the 404 error you're getting, I think [this](https://stackoverflow.com/a/43487798) is the link you're looking for.

Sounds like GitHub Pages ignores the `node_modules` folder by default. Their suggestion is to add an empty file named `.nojekyll`.

If you are planning on adding more npm packages, you should also add a `.gitignore` file so that you aren't committing your entire `node_modules` folder each time.

**Comment by brendaboudaie** [comment]
@frankie-tech thank you!

**Comment by akshikamde21** [comment]
Hi, I am facing the same issue. As told by @frankie-tech i added .nojekyll but the problem still persists. I have bootstrap, jQuery and popper.js inside node_modules. So when I link them on my index.html page, I can see all the bootstrap, jQuery etc that I used properly load in my local host but not on GitHub pages. Also I've added .gitignore which contains node_modules. This is my first project with node and I am not able to understand how to view my site on server because all I see is just html.
